# Generated by Django 3.2.7 on 2021-10-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0002_auto_20211019_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skaut',
            name='slug',
            field=models.SlugField(default='', primary_key=True, serialize=False),
        ),
    ]
