# Generated by Django 3.2.7 on 2021-10-19 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0003_alter_skaut_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oddil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=30)),
                ('vlajka', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='skaut',
            name='oddil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clenove.oddil'),
        ),
    ]
