# Generated by Django 3.2.7 on 2021-10-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0004_auto_20211019_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skaut',
            name='oddil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skauti', to='clenove.oddil'),
        ),
    ]
