# Generated by Django 3.2.7 on 2021-10-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clenove', '0006_auto_20211019_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobrik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dovednost', models.CharField(max_length=200)),
                ('skaut', models.ManyToManyField(to='clenove.Skaut')),
            ],
        ),
    ]
